name: workflows/build-win

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-win:
    name: 'Windows (setup.exe)'
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: git config (rewrite protocol)
        run: git config --global url.https://github.com/.insteadOf git://github.com/
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: '12.22.12'
      - name: install vs 2017 build tools
        run: |
          choco install --no-progress -y visualstudio2017buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.MSBuildTools;includeRecommended --add Microsoft.VisualStudio.Workload.VCTools;includeRecommended --add Microsoft.VisualStudio.Component.VC.140"
      - name: get latest ryo release tag
        run: |
          $L_TAG = & gh release list --repo rtotr/ryo-currency --json tagName,isLatest --jq '.[] | select(.isLatest)|.tagName'
          echo ("LATEST_TAG=$L_TAG") >> $env:GITHUB_ENV
      - name: download latest ryo release
        run: gh release download --repo rtotr/ryo-currency --dir bin --pattern ryo-*-win-x64.7z
      - name: unpack ryo archive
        run: |
          7z x ryo-${{ env.LATEST_TAG }}-win-x64.7z
          Remove-Item ryo-${{ env.LATEST_TAG }}-win-x64.7z
          Get-ChildItem -Path . -File -Name
        working-directory: bin
      - name: npm install
        run: npm install
      - name: build
        run: |
          npm run rebuild
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }} # job names must start with 'build-' for the release workflow to work correctly
          path: dist/electron-mat/Packaged/ryo-wallet-win-x64-setup.zip
