name: workflows/build-mac

on:
  push:
    branches:
      - dev-github-actions-mac
    paths:
      - '**/*-mac.yml'
  workflow_call:
  workflow_dispatch:

jobs:
  build-mac:
    name: 'MacOS (dmg)'
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: git config (rewrite protocol)
        run: git config --global url.https://github.com/.insteadOf git://github.com/
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: '12.22.12'
          architecture: 'x64'
      - name: install cpanm and Mac::Finder::DSStore
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: |
            Mac::Finder::DSStore
      - name: another perl module install attempt
        run: |
          perl -V
          cpanm --version
          cpanm Mac::Finder::DSStore
      - name: get latest ryo release tag
        run: echo "LATEST_TAG=$(gh release list --repo rtotr/ryo-currency --json tagName,isLatest --jq '.[] | select(.isLatest)|.tagName')" >> $GITHUB_ENV
      - name: download latest ryo release
        run: gh release download --repo rtotr/ryo-currency --dir bin --pattern ryo-*-mac-arm64.tar.xz
      - name: unpack ryo archive
        run: |
          tar xf ryo-${{ env.LATEST_TAG }}-mac-arm64.tar.xz ryod ryo-wallet-rpc
          rm ryo-${{ env.LATEST_TAG }}-mac-arm64.tar.xz
          find . -type f
        working-directory: bin
      - name: update versions in packages.json
        if: github.ref_type == 'tag'
        run: |
          jq --arg tag "${{ github.ref_name }}" '.version = $tag' package.json > package.json.tmp && mv package.json.tmp package.json
          jq --arg tag "${{ env.LATEST_TAG }}" '.daemonVersion = $tag' package.json > package.json.tmp && mv package.json.tmp package.json
      - name: npm install
        run: npm install
      - name: build
        run: |
          npm run rebuild
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }} # job names must start with 'build-' for the release workflow to work correctly
          path: dist/electron-mat/Packaged/ryo-wallet-mac-arm64.dmg
