name: workflows/build-linux

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-linux:
    name: 'Ubuntu (AppImage)'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: '12.22.12'
      - name: get latest ryo release tag
        run: echo "LATEST_TAG=$(gh release list --repo rtotr/ryo-currency --json tagName,isLatest --jq '.[] | select(.isLatest)|.tagName')" >> $GITHUB_ENV
      - name: download latest ryo release
        run: gh release download --repo rtotr/ryo-currency --dir bin --pattern ryo-*-linux-x64.tar.xz
      - name: unpack ryo archive
        run: |
          tar xf ryo-${{ env.LATEST_TAG }}-linux-x64.tar.xz
          rm ryo-${{ env.LATEST_TAG }}-linux-x64.tar.xz
          find . -type f
        working-directory: bin
      - name: npm install
        run: npm install
      - name: build
        run: |
          npm run rebuild
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }} # job names must start with 'build-' for the release workflow to work correctly
          path: dist/electron/Packaged/ryo-wallet-linux-x64.AppImage
