name: workflows/create-release

on:
  push:
    tags:
      - '*.*.*.*' # Trigger on version tags

jobs:

  build-all:
    uses: ./.github/workflows/build-all.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build-all
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
    - name: Display build artifacts
      run: |
        pwd
        find . -type f
    - name: Validate tag format
      run: |
        if [[ ! "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: Invalid tag format. Expected format: X.Y.Z.W"
          exit 1
        fi
    - name: Rename artifacts with version number added
      run: |
        find . -type f \( -name "*.AppImage" -o -name "*.exe" -o -name "*.dmg" \) -exec sh -c 'mv "$1" "${1%/*}/ryo-wallet-${{ github.ref_name }}-${1#*ryo-wallet-}"' _ {} \;
        find . -type f
    - name: Create Release
      id: create-release-tag
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build-*/*
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
